"""
inspect_pdf_server.py — FastMCP server exposing one tool: inspect_pdf.

Opens a local PDF with PyMuPDF (fitz) and returns structured prepress
metadata: trim size, bleed presence/adequacy, color-space distribution,
font embedding, and file health. Voomie's agent calls this when a
customer message references an attached PDF.

Reference implementation borrowed from ~/Desktop/Printssistant/preflight_logic.py:
  - L21:    BLEED_MIN_PT = 0.125 * 72 — standard print bleed in points.
  - L107-122: bleed-gap calculation (compare TrimBox to MediaBox with
              0.5pt equality tolerance, then compute per-side gaps).
  - L154-167: image color-space iteration via page.get_images(full=True)
              + doc.extract_image(xref), inspecting `colorspace` (component
              count) and `cs-name`.
That file is for a different use case (it returns pass/warn/fail per
check); we adapt the *fitz call patterns* but emit a different envelope
shape here.

Stdio: JSON-RPC framed by MCP on stdin/stdout. Diagnostic logs go to
stderr so the operator can confirm subprocess identity without polluting
the JSON-RPC channel — same convention as parse_shoptalk_server.py.
"""

from __future__ import annotations

import os
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF

from mcp.server.fastmcp import FastMCP


# Standard print bleed: 0.125 inch == 9 PDF points (1in = 72pt).
# Adapted from Printssistant preflight_logic.py L21.
BLEED_MIN_PT = 0.125 * 72

# Box-equality tolerance: floating-point comparison of TrimBox vs MediaBox.
# Adapted from Printssistant preflight_logic.py L111-112 (0.5pt threshold).
BOX_EQ_TOL_PT = 0.5

# Tolerance when checking individual bleed gaps against BLEED_MIN_PT.
# A 1e-3pt fudge avoids false negatives from PDF round-trip rounding.
BLEED_OK_TOL_PT = 1e-3


# Self-announce identity to stderr before MCP takes over stdin/stdout.
print(
    f"[inspect_pdf_server] PID={os.getpid()} "
    f"fitz={fitz.__version__}",
    file=sys.stderr,
    flush=True,
)


mcp = FastMCP("inspect_pdf_server")


def _boxes_equal(a: fitz.Rect, b: fitz.Rect) -> bool:
    """True if two rects match within BOX_EQ_TOL_PT on width and height.

    fitz's `page.trimbox` falls back to MediaBox when TrimBox is unset, so
    equality (within tolerance) is how we detect "no TrimBox declared".
    """
    return (
        abs(a.width - b.width) < BOX_EQ_TOL_PT
        and abs(a.height - b.height) < BOX_EQ_TOL_PT
        and abs(a.x0 - b.x0) < BOX_EQ_TOL_PT
        and abs(a.y0 - b.y0) < BOX_EQ_TOL_PT
    )


def _font_embedded(font_tuple: tuple) -> bool:
    """Decide if a font tuple from doc.get_page_fonts() is embedded.

    fitz tuple shape: (xref, ext, type, basefont, name, encoding, [referencer]).
    Empty ext or "n/a" means the font is referenced but its program is not
    embedded in the PDF — typical for the 14 standard PDF fonts (Helvetica,
    Times, Courier, etc) that downstream consumers must supply.

    The task spec mentioned an "element index 7 = 'embedded'" pattern from
    older fitz docs; current fitz (1.27.x) uses index 1 (`ext`) as the
    embedding signal — confirmed empirically against fitz 1.27.2.3 on
    PDFs generated by both reportlab and fitz itself. Standard fonts
    report ext='n/a'; embedded subsets report ext='ttf'/'otf'/'cff'.
    """
    if len(font_tuple) < 2:
        return False
    ext = font_tuple[1]
    return bool(ext) and ext != "n/a"


def _font_name(font_tuple: tuple) -> str:
    """Pull the most useful display name from a fitz font tuple.

    Index 3 is the basefont (e.g. "VNXCVS+ArialMT" for embedded subsets),
    index 4 is the in-document reference name (e.g. "helv"). Prefer basefont.
    """
    if len(font_tuple) >= 4 and font_tuple[3]:
        return font_tuple[3]
    if len(font_tuple) >= 5 and font_tuple[4]:
        return font_tuple[4]
    return "unknown"


def _classify_image_colorspace(img_dict: dict) -> str | None:
    """Return 'rgb', 'cmyk', 'grayscale', or None for an extracted image.

    Adapted from Printssistant preflight_logic.py L154-167. fitz's
    extract_image() returns:
      - colorspace: int component count (1=Gray, 3=RGB, 4=CMYK, 0=unknown)
      - cs-name:    string like "DeviceRGB", "ICCBased(CMYK,...)", "DeviceCMYK"
    Component count is the primary signal; cs-name is the secondary
    fallback for ICC-based profiles where component count may be reported
    as the underlying device space.
    """
    comps = img_dict.get("colorspace", 0)
    cs_name = (img_dict.get("cs-name") or "").lower()
    if comps == 4 or "cmyk" in cs_name:
        return "cmyk"
    if comps == 3 or "rgb" in cs_name:
        return "rgb"
    if comps == 1 or "gray" in cs_name or "devicegray" in cs_name:
        return "grayscale"
    return None


def _err(file_path: str, error_class: str, message: str) -> dict[str, Any]:
    return {
        "ok": False,
        "file_path": file_path,
        "error_class": error_class,
        "message": message,
    }


@mcp.tool()
def inspect_pdf(file_path: str) -> dict[str, Any]:
    """Inspect a PDF file and return structured metadata including trim
    size, bleed presence, color space, font embedding, and file health.
    Call this when a customer message references an attached PDF. Returns
    warnings for common prepress issues the agent should surface to the
    customer.

    Argument:
      file_path — absolute path on the local filesystem.

    Success shape:
      {ok: true, file_path, page_count, trim_size, bleed, color_space,
       fonts, file_health, warnings}

    Error shape:
      {ok: false, file_path,
       error_class: "encrypted" | "corrupted" | "not_found" | "not_pdf"
                    | "internal_error",
       message: <human-readable>}
    """
    # 1. Path-shape validation. Fail fast on .jpg/.png/.ai/.indd before
    #    handing the file to fitz — saves a noisy fitz error and lets us
    #    return the user-friendly "ask the customer for a PDF" message.
    p = Path(file_path)
    suffix_lc = p.suffix.lower()
    if suffix_lc != ".pdf":
        return _err(
            file_path,
            "not_pdf",
            f"File is {p.suffix or '(no extension)'} — please ask the "
            "customer to provide a PDF.",
        )

    if not p.exists():
        return _err(
            file_path,
            "not_found",
            f"No file at {file_path}",
        )

    # 2. Open with fitz. Anything fitz throws here is a corruption symptom
    #    — bad header, truncated stream, malformed xref. Surface as
    #    "corrupted" so the agent can ask the customer for a fresh export.
    try:
        doc = fitz.open(str(p))
    except Exception as e:  # noqa: BLE001 — fitz raises a variety of unrelated types
        return _err(file_path, "corrupted", f"Could not open PDF: {e}")

    try:
        # 3. Encryption check BEFORE reading content. fitz will let you
        #    open an encrypted PDF but rendering/extracting raises until
        #    authenticated — fail fast with a structured error.
        if doc.is_encrypted:
            return _err(
                file_path,
                "encrypted",
                "PDF is password-protected. Ask the customer to send an "
                "unencrypted version.",
            )

        page_count = len(doc)
        if page_count == 0:
            return _err(
                file_path,
                "corrupted",
                "PDF has 0 pages.",
            )

        # 4. Trim size from page 0. Per spec: read trimbox, fall back to
        #    mediabox if unset (fitz's trimbox auto-falls-back, so we use
        #    box equality with BOX_EQ_TOL_PT to detect that case).
        page0 = doc[0]
        mb = page0.mediabox
        tb = page0.trimbox
        trimbox_set = not _boxes_equal(tb, mb)

        # If TrimBox is unset, the spec says fall back to MediaBox for
        # the *trim* dimensions — so width/height come from the active
        # box, not from tb specifically.
        active_box = tb if trimbox_set else mb
        width_pt = active_box.width
        height_pt = active_box.height

        # 5. Bleed gaps — only meaningful when TrimBox is actually set.
        #    Adapted from Printssistant L118-122.
        if trimbox_set:
            left_pt = tb.x0 - mb.x0
            bottom_pt = tb.y0 - mb.y0
            right_pt = mb.x1 - tb.x1
            top_pt = mb.y1 - tb.y1
            sides_pt = {
                "top": top_pt,
                "bottom": bottom_pt,
                "left": left_pt,
                "right": right_pt,
            }
            adequate = all(
                g >= BLEED_MIN_PT - BLEED_OK_TOL_PT for g in sides_pt.values()
            )
            bleed_present = True
        else:
            sides_pt = {"top": 0.0, "bottom": 0.0, "left": 0.0, "right": 0.0}
            adequate = False
            bleed_present = False

        # 6. Color-space distribution across ALL pages, ALL images.
        #    cs-counts seeds the 'dominant' decision; presence flags drive
        #    has_rgb / has_cmyk / has_grayscale / mixed.
        cs_counts: Counter[str] = Counter()
        for page in doc:
            for img_info in page.get_images(full=True):
                xref = img_info[0]
                try:
                    img = doc.extract_image(xref)
                except Exception:
                    # A broken image stream isn't fatal for the rest of the
                    # inspection — skip it and keep going.
                    continue
                kind = _classify_image_colorspace(img)
                if kind is not None:
                    cs_counts[kind] += 1

        has_rgb = cs_counts.get("rgb", 0) > 0
        has_cmyk = cs_counts.get("cmyk", 0) > 0
        has_grayscale = cs_counts.get("grayscale", 0) > 0
        present_kinds = sum(1 for v in (has_rgb, has_cmyk, has_grayscale) if v)
        mixed = present_kinds > 1

        if cs_counts:
            top_key = cs_counts.most_common(1)[0][0]
            dominant = {"rgb": "RGB", "cmyk": "CMYK", "grayscale": "Grayscale"}[top_key]
        else:
            dominant = None

        # 7. Font embedding across all pages. Dedupe by name so a font that
        #    appears on 5 pages doesn't show up 5 times in unembedded_names.
        embedded_count = 0
        unembedded_seen: set[str] = set()
        for pno in range(page_count):
            for ft in doc.get_page_fonts(pno):
                if _font_embedded(ft):
                    embedded_count += 1
                else:
                    unembedded_seen.add(_font_name(ft))
        unembedded_names = sorted(unembedded_seen)
        all_embedded = len(unembedded_names) == 0

        # 8. File health (we already passed encrypt/corrupt checks above).
        pdf_version = "unknown"
        if doc.metadata:
            pdf_version = doc.metadata.get("format") or "unknown"

        # 9. Human-readable warnings. The agent surfaces these to the
        #    customer; the spec lists the exact phrasings we should emit.
        warnings: list[str] = []
        if not trimbox_set:
            warnings.append("TrimBox not set, using MediaBox for trim size")
        if mixed:
            warnings.append("Mixed color spaces detected — check for RGB elements")
        if bleed_present and not adequate:
            thin = [
                s for s, g in sides_pt.items()
                if g < BLEED_MIN_PT - BLEED_OK_TOL_PT
            ]
            warnings.append(
                "Bleed present but less than 0.125in on "
                f"{', '.join(thin)} side"
            )
        if unembedded_names:
            warnings.append(
                "Font embedding could not be verified for: "
                + ", ".join(unembedded_names)
            )

        return {
            "ok": True,
            "file_path": file_path,
            "page_count": page_count,
            "trim_size": {
                "width_in": round(width_pt / 72.0, 4),
                "height_in": round(height_pt / 72.0, 4),
                "width_pt": round(width_pt, 4),
                "height_pt": round(height_pt, 4),
            },
            "bleed": {
                "present": bleed_present,
                "top_in": round(sides_pt["top"] / 72.0, 4),
                "bottom_in": round(sides_pt["bottom"] / 72.0, 4),
                "left_in": round(sides_pt["left"] / 72.0, 4),
                "right_in": round(sides_pt["right"] / 72.0, 4),
                "adequate": adequate,
            },
            "color_space": {
                "dominant": dominant,
                "has_rgb": has_rgb,
                "has_cmyk": has_cmyk,
                "has_grayscale": has_grayscale,
                "mixed": mixed,
            },
            "fonts": {
                "all_embedded": all_embedded,
                "embedded_count": embedded_count,
                "unembedded_names": unembedded_names,
            },
            "file_health": {
                "encrypted": False,
                "corrupted": False,
                "pdf_version": pdf_version,
            },
            "warnings": warnings,
        }
    except Exception as e:  # noqa: BLE001
        return _err(file_path, "internal_error", f"{type(e).__name__}: {e}")
    finally:
        doc.close()


if __name__ == "__main__":
    mcp.run()
